WebApp/Models/ErrorViewModel.cs
namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApp/Controllers/MetricsController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers;

public class MetricsController : Controller
{
    private readonly ILogger<MetricsController> _logger;

    public MetricsController(ILogger<MetricsController> logger)
    {
        _logger = logger;
    }

    [HttpGet("/metrics")]
    public IActionResult Metrics()
    {
        return View();
    }
}

WebApp/Controllers/ProductCatalogController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Domain;

namespace WebApp.Controllers;

public class ProductCatalogController : Controller
{
    private readonly ILogger<ProductCatalogController> _logger;
    private readonly IProductService _productService;

    public ProductCatalogController(
        IProductService productService,
        ILogger<ProductCatalogController> logger)
    {
        ArgumentNullException.ThrowIfNull(productService);
        ArgumentNullException.ThrowIfNull(logger);

        _productService = productService;
        _logger = logger;
    }

    [HttpGet]
    public async Task<ActionResult<IReadOnlyCollection<ProductResponse>>> Products(CancellationToken cancelToken = default)
    {
        var products = await _productService.GetAll(cancelToken);
        return View(products);
    }

    [HttpGet]
    public IActionResult ProductAddition() => View();

    [HttpPost]
    public async Task<IActionResult> ProductAddition(
        [FromForm] ProductToCreate product, 
        CancellationToken cancellationToken = default)
    {
        try
        {
            await _productService.Add(product, cancellationToken);
        }
        catch (OperationCanceledException)
        {
            _logger.LogInformation("Operation was cancelled.");
            return View();
        }
        catch (ArgumentNullException ex)
        {
            _logger.LogInformation(ex, ex.Message);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, ex.Message);
        }

        return View();
    }
}

WebApp/Views/Home/Index.cshtml
<h1>Home page</h1>

WebApp/Views/Metrics/Metrics.cshtml
<div>Current page will be enable soon.</div>

WebApp/Views/ProductCatalog/ProductAddition.cshtml
@{ ViewData["Title"] = "Product addition"; }

<form method="post">
    <label>Title</label>
    <input type="text" name="Title" required/>
    <br/>
    <label>ImageUrl</label>
    <input type="url", name="Image"/>
    <br/>
    <input type="submit", name="submit" value="Append"/>
</form>

WebApp/Views/ProductCatalog/Products.cshtml
@using WebApp.Domain
@model IReadOnlyCollection<ProductResponse>

@{ ViewData["Title"] = "Products"; }

@foreach (var item in Model)
{
    <img src="@item.Image" width="80" height="80"/>
    <div>Title: @item.Title</div>
}
<br/>
<div>Products count: @Model.Count</div>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductCatalog" asp-action="Products">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductCatalog" asp-action="ProductAddition">ProductAddition</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Metrics" asp-action="Metrics">Metrics</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Index">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>